export default {
    toolbar: {
        items: [
            'revisionHistory',
            '|',
            'heading',
            'horizontalLine',
            '|',
            'link',
            '|',
            'bold',
            'italic',
            'alignment',
            'subscript',
            'superscript',
            'underline',
            'strikethrough',
            '|',
            'blockQuote',
            'bulletedList',
            'numberedList',
            '|',
            'insertTable',
            'mediaBrowser',
            'mediaEmbed',
            '|',
            'snippetBrowser',
            'htmlEmbed',
            '|',
            'trackChanges',
            '|',
            'comment',
            '|',
            'undo',
            'redo'
        ]
    },
}
